pipeline:
  build:
     image: docker
     script:
       - docker build .  
  docker:
    image: drone-docker
    registry: https://gitlab.com
    repo: registry.gitlab.com/cabhi/drone-test1
    username: cabhi
    password: Xampp_11
    email: abhishek.ch.3@gmail.com
    file: drone-test1/Dockerfile 
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    tags:
      - 1.1
